/* -*- C++ -*- */
/* Generated by opendds_idl version 3.21.0 (ACE version 6.5.18) running on input file ../tests/ROS2/String.idl */
#ifndef OPENDDS_IDL_GENERATED_STRINGC_H_CELRIJ
#define OPENDDS_IDL_GENERATED_STRINGC_H_CELRIJ
#include <cstdint>
#include <string>
#include <utility>


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: std_msgs */



/* Begin MODULE: msg */



/* Begin MODULE: dds_ */



/* Begin STRUCT: String_ */

namespace std_msgs {
namespace msg {
namespace dds_ {

class String_
{
public:

  void data(const std::string& val) { _data = val; }
  void data(std::string&& val) { _data = std::move(val); }
  const std::string& data() const { return _data; }
  std::string& data() { return _data; }
  std::string _data;

  String_() = default;
  explicit String_(const std::string& data);

};

void swap(String_& lhs, String_& rhs);

}
}
}

/* End STRUCT: String_ */

/* End MODULE: dds_ */

/* End MODULE: msg */

/* End MODULE: std_msgs */
#endif /* OPENDDS_IDL_GENERATED_STRINGC_H_CELRIJ */
